name: Deploy Frontend

on:
  push:
    branches: ['prod', 'main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Navigate to the frontend directory inside the main repository on the server
            cd ~/projects/rountin-cafe/frontend
            git pull origin prod

            # Go back to the parent directory where deploy.sh and docker-compose.yaml are located
            cd ..
            sh deploy.sh
